name: Build bookdown image
on:
  schedule:
    - cron: '30 23 * * *'
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: docker login -u "${{ secrets.DOCKER_ID }}" -p "${{ secrets.DOCKER_PW }}"
      - name: Build image
        run: docker build -t ${{ secrets.DOCKER_ID }}/bookdown:$(date +%Y%m%d) .
      - name: Tag image
        run: docker tag ${{ secrets.DOCKER_ID }}/bookdown:$(date +%Y%m%d) ${{ secrets.DOCKER_ID }}/bookdown
      - name: Push image
        run: |
          docker push ${{ secrets.DOCKER_ID }}/bookdown:$(date +%Y%m%d)
          docker push ${{ secrets.DOCKER_ID }}/bookdown
