name: Build image
on:
  schedule:
    - cron: '30 23 * * *'
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      USER: ${{ secrets.DOCKER_ID }}
      PASS: ${{ secrets.DOCKER_PW }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: docker login -u "$USER" -p "$PASS"
      - name: Build and push image
        run: USER=$USER make
