name: Build image
on:
  schedule:
    - cron: '30 23 * * *'
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      USER: ${{ secrets.DOCKER_ID }}
      PASS: ${{ secrets.DOCKER_PW }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: docker login -u "$USER" -p "$PASS"
      - name: Build image
        run: docker build -t "$USER/bookdown" .
      - name: Tag image
        run: docker tag "$USER/bookdown" "$USER/bookdown:$(date +%Y%m%d)"
      - name: Push image
        run: docker push -a "$USER/bookdown"
