name: Build bookdown image
on:
  schedule:
    - cron: '30 23 * * *'
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_ID }} -p ${{ secrets.DOCKER_PW }}
      - name: Build image
        run: docker build -t bookdown:$(date +%Y%m%d) .
      - name: Push image
        run: docker push bookdown:$(date +%Y%m%d)
